### ISSUE TITLE
Random issue with pps_shutter

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-XFP/profile_collection#8]
Randomly got this today during running of the alignment procedure:
```py
shutter Close 139733943670096
pps_shutter Close 139733943025168
** (2018-04-12 14:32:23) Had to reactuate shutter while Closing
pps_shutter Close 139733943135424
Traceback (most recent call last):
  File "/home/xf17bm/.ipython/profile_collection/startup/99-gui-ht.py", line 587, in align_ht
    RE(align_ht(**kwargs))
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/run_engine.py", line 669, in __call__
    raise exc
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/run_engine.py", line 1117, in _run
    raise err
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/run_engine.py", line 995, in _run
    self._exception)
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 1238, in __call__
    return (yield from plan)
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 1092, in baseline_wrapper
    return (yield from plan)
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 724, in monitor_during_wrapper
    return (yield from plan2)
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 75, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 75, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 782, in fly_during_wrapper
    return (yield from plan2)
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 75, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 75, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/xf17bm/.ipython/profile_collection/startup/97-align-ht.py", line 52, in align_ht
    close_shutters())
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 453, in finalize_wrapper
    yield from ensure_generator(final_plan_instance)
  File "/home/xf17bm/.ipython/profile_collection/startup/97-align-ht.py", line 26, in close_shutters
    yield from bps.mv(pps_shutter, 'Close')
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/plan_stubs.py", line 244, in mv
    yield Msg('wait', None, group=group)
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 163, in plan_mutator
    inner_ret = yield msg
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 163, in plan_mutator
    inner_ret = yield msg
  File "/opt/conda_envs/collection-2018-1.0/lib/python3.6/site-packages/bluesky/preprocessors.py", line 163, in plan_mutator
    inner_ret = yield msg
bluesky.utils.FailedStatus: DeviceStatus(device=pps_shutter, done=True, success=False)

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

In [2]:

In [2]: pps_shutter
Out[2]: TwoButtonShutter(prefix='XF:17BM-PPS{Sh:FE}', name='pps_shutter', read_attrs=['status'], configuration_attrs=[])

In [3]: pps_shutter.status
Out[3]: EpicsSignalRO(read_pv='XF:17BM-PPS{Sh:FE}Pos-Sts', name='pps_shutter_status', parent='pps_shutter', value='Not Open', timestamp=1523557945.098395, pv_kw={}, auto_monitor=False, string=True)

In [5]: pps_shutter.status.read()
Out[5]: {'pps_shutter_status': {'timestamp': 1523557945.098395, 'value': 'Not Open'}}
```
@tacaswell, can it be related to the TwoButtonShutter?

**Comment by erikfarquhar** [comment]
Have seen this recur a couple of times a year since originally reported (i.e., once in a blue moon). 
It's so rare that it's probably not worth chasing after.

**Comment by erikfarquhar** [comment]
Go figure, I make the above comment and have it happen to me just now. Interestingly, the PPS shutter did actually show as open, but the alignment scan failed - moved to the alignment position with PPS shutter open, then immediately moved back to the load position, closing the PPS shutter as part of clean-up. Here's the error code dump:

```
pps_shutter Open 140186396995408
** (2020-11-09 17:14:31) Had to reactuate shutter while Opening
** (2020-11-09 17:14:32) Had to reactuate shutter while Opening
** (2020-11-09 17:14:34) Had to reactuate shutter while Opening
pps_shutter Close 140186392303120
** (2020-11-09 17:14:53) Had to reactuate shutter while Closing
** (2020-11-09 17:14:54) Had to reactuate shutter while Closing
Traceback (most recent call last):
  File "/home/xf17bm/.ipython/profile_collection/startup/99-gui-ht.py", line 676, in align_ht
    RE(align_ht(**kwargs))
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 807, in __call__
    self._resume_task(init_func=_build_task)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 931, in _resume_task
    raise exc
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1500, in _run
    raise err
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1365, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1307, in __call__
    return (yield from plan)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1160, in baseline_wrapper
    return (yield from plan)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 861, in fly_during_wrapper
    return (yield from plan2)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/xf17bm/.ipython/profile_collection/startup/97-align-ht.py", line 90, in align_ht
    close_shutters())
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/home/xf17bm/.ipython/profile_collection/startup/97-align-ht.py", line 68, in main_plan
    yield from bps.mv(pps_shutter, 'Open')
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 258, in mv
    yield Msg('wait', None, group=group)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  [Previous line repeated 1 more time]
bluesky.utils.FailedStatus: DeviceStatus(device=pps_shutter, done=True, success=False)

If you suspect this is an IPython 7.18.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by erikfarquhar** [comment]
A different PPS shutter issue, encountered today. In this one, completed an exposure series, at which point the pre-shutter and PPS shutter close, then the stage moves back to the load position. Saw both shutters close, then the console output below appeared and the stage remained at the last exposure slot. Moved back to load position manually and re-ran the experiment again as a test, with no issues. Assume it is a recurrence of the shutter gremlins . . . .

```
UID from xfp_plan_fast_shutter(): 01f57879-d70c-4244-b34a-129c8b9c72d1
pps_shutter Open 140489339115472
** (2020-11-10 17:34:22) Had to reactuate shutter while Opening
shutter Open 140489339759376
** (2020-11-10 17:34:38) Had to reactuate shutter while Opening
shutter Close 140489725509520
pps_shutter Close 140489767578384
** (2020-11-10 17:38:26) Had to reactuate shutter while Closing
** (2020-11-10 17:38:28) Had to reactuate shutter while Closing
** (2020-11-10 17:38:29) Had to reactuate shutter while Closing
pps_shutter Close 140489729365584
Traceback (most recent call last):
  File "/home/xf17bm/.ipython/profile_collection/startup/99-gui-ht.py", line 378, in run
    self.RE(self.GUI.plan())
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 807, in __call__
    self._resume_task(init_func=_build_task)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 931, in _resume_task
    raise exc
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1500, in _run
    raise err
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1342, in _run
    stashed_exception or resp)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1307, in __call__
    return (yield from plan)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1160, in baseline_wrapper
    return (yield from plan)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 861, in fly_during_wrapper
    return (yield from plan2)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/xf17bm/.ipython/profile_collection/startup/99-gui-ht.py", line 786, in plan
    close_shutters()))
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 528, in finalize_wrapper
    yield from ensure_generator(final_plan_instance)
  File "/home/xf17bm/.ipython/profile_collection/startup/99-gui-ht.py", line 700, in close_shutters
    yield from bps.mv(pps_shutter, 'Close')
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 256, in mv
    ret = yield Msg('set', obj, val, group=group, **kwargs)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  [Previous line repeated 1 more time]
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1425, in _run
    new_response = await coro(msg)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1921, in _set
    ret = msg.obj.set(*msg.args, **kwargs)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/nslsii/devices.py", line 31, in set
    raise RuntimeError(f'trying to set {self.name}'
RuntimeError: trying to set pps_shutter while a set is in progress

If you suspect this is an IPython 7.18.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

In [3]: %tb
RuntimeError: trying to set pps_shutter while a set is in progress


In [4]:
```

**Comment by erikfarquhar** [comment]
Fault noted in previous comment recurred today, with exactly the same behavior (completed last slot exposure, closed both shutters, then threw errors and did not return to load position). This possibly seems to be an ophyd issue and not something with the PPS shutter, but we can bring the PPS group into the discussion.

```
Slot #30: X=38.736691256354746  Y=-49.04416025448617
UID from xfp_plan_fast_shutter(): 1e8b4265-aea3-405c-8178-a7d5339ebc95
Info: {'plan_name': 'ht', 'reason': 'B-exposures-20Nov2020', 'exposure': 40.0, 'position': 31, 'filter_index': 4, 'filter_text': 'Angle: 180 [deg] Thickness: 203 [um]', 'name': 'ZnFXII-D04-uPar-exp-203', 'notes': '3uM wtFXII + 15uM D04+ 6uM Upar 10uM ZnCl2 in 1X PBS, pH 7.4, 203um Al'}
Slot #31: X=47.736691256354746  Y=-49.04416025448617
UID from xfp_plan_fast_shutter(): d7485880-e093-4982-a72c-e5de22db405d
pps_shutter Open 140420550649616
** (2020-11-20 14:41:51) Had to reactuate shutter while Opening
shutter Open 140420550666576
** (2020-11-20 14:42:08) Had to reactuate shutter while Opening
shutter Close 140420547784400
pps_shutter Close 140420549779280
** (2020-11-20 14:43:22) Had to reactuate shutter while Closing
** (2020-11-20 14:43:24) Had to reactuate shutter while Closing
** (2020-11-20 14:43:25) Had to reactuate shutter while Closing
pps_shutter Close 140420547812880
Traceback (most recent call last):
  File "/home/xf17bm/.ipython/profile_collection/startup/99-gui-ht.py", line 378, in run
    self.RE(self.GUI.plan())
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 807, in __call__
    self._resume_task(init_func=_build_task)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 931, in _resume_task
    raise exc
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1500, in _run
    raise err
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1342, in _run
    stashed_exception or resp)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1307, in __call__
    return (yield from plan)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1160, in baseline_wrapper
    return (yield from plan)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 861, in fly_during_wrapper
    return (yield from plan2)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/xf17bm/.ipython/profile_collection/startup/99-gui-ht.py", line 786, in plan
    close_shutters()))
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 528, in finalize_wrapper
    yield from ensure_generator(final_plan_instance)
  File "/home/xf17bm/.ipython/profile_collection/startup/99-gui-ht.py", line 700, in close_shutters
    yield from bps.mv(pps_shutter, 'Close')
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 256, in mv
    ret = yield Msg('set', obj, val, group=group, **kwargs)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  [Previous line repeated 1 more time]
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1425, in _run
    new_response = await coro(msg)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/bluesky/run_engine.py", line 1921, in _set
    ret = msg.obj.set(*msg.args, **kwargs)
  File "/opt/conda_envs/collection-2020-2.0rc8/lib/python3.7/site-packages/nslsii/devices.py", line 31, in set
    raise RuntimeError(f'trying to set {self.name}'
RuntimeError: trying to set pps_shutter while a set is in progress

If you suspect this is an IPython 7.18.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

In [2]: %tb
RuntimeError: trying to set pps_shutter while a set is in progress


In [3]: 
```

**Comment by erikfarquhar** [comment]
EPS PLC bugfixes appear to have resolved this issue.
